# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LeanChat' do
    pod 'AVOSCloud'
    pod 'AVOSCloudIM'
    pod 'LeanChatLib'
    pod 'MBProgressHUD'
    pod 'LZAlertViewHelper' , '~> 0.0.2'
    pod 'JSBadgeView'
    pod 'LZMembersCell'
end

target 'LeanChatTests' do

end

