# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LeanChatLib' do
    pod 'AVOSCloud', '~> 3.1.2.4'
    pod 'AVOSCloudIM', '~> 3.1.2.4'
    pod 'LZConversationCell', '~> 0.0.1'
    pod 'DateTools' , '~> 1.5.0'
end

