# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LeanChatLib' do
    pod 'AVOSCloud'
    pod 'AVOSCloudIM'
    pod 'JSBadgeView'
    pod 'FMDB'
    pod 'LZConversationCell'
end

target 'LeanChatLibTests' do

end

